name: CI/CD

on:
  push:
    branches: [ main ]
    # branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: yarn install

    # - name: Run the tests and generate coverage report
    #   run: npm test -- --coverage

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1

    - name: Build
      run: yarn build

    - name: Deploy
      run: |
        # git config --global user.name $user_name
        # git config --global user.email $user_email
        # git remote set-url origin https://${github_token}@github.com/${repository}
        yarn deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        # user_name: 'github-actions[bot]'
        # user_email: 'github-actions[bot]@users.noreply.github.com'
        # github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        # repository: ${{ github.repository }}
